# Configuracion para el acceso a la Base de Datos
spring.jpa.hibernate.ddl-auto=validate

# Puerto por donde escucha el servidor cuando se inicie
server.port=5000

# Path de la web API
spring.data.rest.base-path=/api

#Lengua local del proyecto
spring.web.locale=es_ES
spring.web.locale-resolver=fixed

#Version de la API
spring.application.version=1.0.0

# Datos de conexion con la base de datos MariaDB
spring.datasource.url=jdbc:mariadb://44.216.137.25:3306/pocketTrack
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=Ivan
spring.datasource.password=12345

# Muestra las query SQL que ejecuta Hibernate
spring.jpa.show-sql=true

# Habilitar Flyway
spring.flyway.enabled=true
# Ejecutar flyway.repair() automaticamente antes de migrar (opcional)
spring.flyway.repair-on-migrate=true
# Ubicacion de los scripts de migracion
spring.flyway.locations=classpath:db/migration

#Oculta el schema de swagger (los tipos de datos)
springdoc.swagger-ui.default-models-expand-depth=-1

jwt.secret = 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
jwt.expiration = 36000
logging.level.org.springdoc=DEBUG